// Feed
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS'
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE'
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS'
export const UNSUBSCRIBE_FAILURE = 'UNSUBSCRIBE_FAILURE'
export const RECEIVE_FEED = 'RECEIVE_FEED'
export const SEARCHING_START = 'SEARCHING_START'
export const SEARCHING_END = 'SEARCHING_END'
export const UPDATE_URL = 'UPDATE_URL'
// Feeds
export const RECEIVE_FEEDS = 'RECEIVE_FEEDS'
export const getPopularFeeds = 'getPopularFeeds'
// Post
export const MARK_SUCCESS = 'MARK_SUCCESS'
export const MARK_FAILURE = 'MARK_FAILURE'
export const LOVE_SUCCESS = 'LOVE_SUCCESS'
export const LOVE_FAILURE = 'LOVE_FAILURE'
export const READ_POST = 'READ_POST'
// Posts
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_POST = 'RECEIVE_POST'
export const RECEIVE_RECENT_POSTS = 'RECEIVE_RECENT_POSTS'
export const RECEIVE_FEED_POSTS = 'RECEIVE_FEED_POSTS'
export const READ_ALL_SUCCESS = 'READ_ALL_SUCCESS'
export const READ_ALL_FAILURE = 'READ_ALL_FAILURE'
// User
export const RECEIVE_USER = 'RECEIVE_USER'
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const INPUT_USERNAME = 'INPUT_USERNAME'
// Global
export const EXPAND = 'EXPAND'
export const COLLAPSE = 'COLLAPSE'
export const ERROR = 'ERROR'
export const INFO = 'INFO'
export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'
export const INPUT_EMAIL = 'INPUT_EMAIL'
export const INPUT_PASSWORD = 'INPUT_PASSWORD'
export const ONLINE = 'ONLINE'
export const OFFLINE = 'OFFLINE'
export const CLEAR_ERROR = 'CLEAR_ERROR'